server:
  servlet:
    context-path: /api/upload
spring:
  datasource:
    url: jdbc:h2:mem:upload-api
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

aws:
  region: us-east-1
  bucketName: ${BUCKET_NAME}
  key: ${ACCESS_KEY}
  secret: ${SECRET_KEY}
  sqs:
    queue-upload: https://sqs.us-east-1.amazonaws.com/438365882822/video-upload
    queue-update: https://sqs.us-east-1.amazonaws.com/438365882822/video-updated

integrations:
  baseUrl: http://localhost:8081

jwt:
  public-key: public-key.pem
